[package]
name = "rat-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
hex.workspace = true
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
