[package]
name = "rat-config"
version = "0.1.0"
edition = "2021"

[dependencies]
rat-protocol = { path = "../rat-protocol" }
humantime.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
toml_edit.workspace = true
