[package]
name = "rat-transport"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes.workspace = true
futures-util.workspace = true
tracing.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
