[project]
name = "mock_foxglove"
scan_root = "."
recursive = true
extensions = [".h", ".c"]
ignore_dirs = ["target", ".git"]

[artifacts]
elf = ""
hex = ""
bin = ""

[generation]
out_dir = "."
toml_name = "rat_gen.toml"
header_name = "rat_gen.h"

[rttd]
text_id = 255

[rttd.server]
addr = "127.0.0.1:19021"
reconnect = "1s"
buf = 256
reader_buf = 65536

[rttd.server.backend]
type = "none"
auto_start = false
startup_timeout_ms = 5000

[rttd.server.backend.openocd]
elf = ""
symbol = "_SEGGER_RTT"
interface = "interface/cmsis-dap.cfg"
target = "target/stm32f4x.cfg"
transport = "swd"
speed = 8000
polling = 1
disable_debug_ports = true

[rttd.server.backend.jlink]
device = "STM32F407ZG"
interface = "SWD"
speed = 4000
serial = ""
ip = ""
rtt_telnet_port = 19021

[rttd.foxglove]
ws_addr = "127.0.0.1:8765"
