[meta]
project = "mock_foxglove"
schema_hash = "0x6DC228D8526C7443"

[[packets]]
id = 116
struct_name = "Attitude"
type = "quat"
packed = false
byte_size = 16
source = "mock_packets.h"

[[packets.fields]]
name = "x"
c_type = "float"
offset = 0
size = 4

[[packets.fields]]
name = "y"
c_type = "float"
offset = 4
size = 4

[[packets.fields]]
name = "z"
c_type = "float"
offset = 8
size = 4

[[packets.fields]]
name = "w"
c_type = "float"
offset = 12
size = 4

[[packets]]
id = 34
struct_name = "Temperature"
type = "plot"
packed = false
byte_size = 8
source = "mock_packets.h"

[[packets.fields]]
name = "celsius"
c_type = "float"
offset = 0
size = 4

[[packets.fields]]
name = "tick_ms"
c_type = "uint32_t"
offset = 4
size = 4

[[packets]]
id = 118
struct_name = "Waveform"
type = "plot"
packed = false
byte_size = 8
source = "mock_packets.h"

[[packets.fields]]
name = "value"
c_type = "float"
offset = 0
size = 4

[[packets.fields]]
name = "tick_ms"
c_type = "uint32_t"
offset = 4
size = 4

[[packets]]
id = 217
struct_name = "ImageStats"
type = "image"
packed = true
byte_size = 9
source = "mock_packets.h"

[[packets.fields]]
name = "width"
c_type = "uint16_t"
offset = 0
size = 2

[[packets.fields]]
name = "height"
c_type = "uint16_t"
offset = 2
size = 2

[[packets.fields]]
name = "frame_idx"
c_type = "uint32_t"
offset = 4
size = 4

[[packets.fields]]
name = "luma"
c_type = "uint8_t"
offset = 8
size = 1
